config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :feedbacks
  resources :posts
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @feedbacks = Feedback.all
  end

  def show
    @feedback = Feedback.find(params[:id])
  end
  
  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy
    redirect_to feedback_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post,notice: "post atualizado com sucesso"
    else 
      render :edit
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post,notice: "post criado com sucesso"
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url,notice: "post deletado com sucesso"
  end

  private 
    def set_post 
      @post = Post.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/feedbacks/create.html.erb
<h1>Feedbacks#create</h1>
<p>Find me in app/views/feedbacks/create.html.erb</p>

app/views/feedbacks/destroy.html.erb
<h1>Feedbacks#destroy</h1>
<p>Find me in app/views/feedbacks/destroy.html.erb</p>

app/views/feedbacks/edit.html.erb
<h1>Feedbacks#edit</h1>
<p>Find me in app/views/feedbacks/edit.html.erb</p>

app/views/feedbacks/index.html.erb
<h1>Feedbacks</h1>
<%= link_to "Criar feedback",new_feedback_path%>
<table class="table text-light">
  <thead>
    <tr>
      <th>nome</th>
      <th>desc</th>
      <th>data</th>
      <th>resolvido</th>
      <th>usuario</th>
      <th colspan="3"></th>
    <tr>
  </thead>
  <tbody data-target="feedback.row" data-action="click->feedback#show">
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.nome %></td>
        <td><%= feedback.desc %></td>
        <td><%= feedback.data %></td>
        <td><%= feedback.resolvido %></td>
        <td><%= feedback.usuario %></td>
        <td><%= link_to "Mostrar",feedback%></td>
        <td><%= link_to "Editar",edit_feedback_path(feedback) %></td>
        <td><%= button_to "Deletar",feedback,method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feedbacks/new.html.erb
<h1>Crie seu feedback</h1>
<%= form_with model: @feedback,data: {type: :hotwire} do |form| %>
  <div class="field">
    <%= form.label :nome%>
    <%= form.text_field :nome%>
  </div>
  <div class="field">
    <%= form.label :desc%>
    <%= form.text_area :desc%>
  </div>
  <div class="field">
    <%= form.label :data%>
    <%= form.datetime_local_field  :data%>
  </div>
  <div class="field">
    <%= form.label :resolvido%>
    <%= form.radio_button  :resolvido%>
  </div>
  <div class="field">
    <%= form.label :usuario%>
    <%= form.text_field :usuario%>
  </div>
<% end %>
<%= link_to "voltar",feedbacks_path %>

app/views/feedbacks/show.html.erb
<h1>Mostrando o feedback</h1>
<h2><%= @feedback.nome %></h2>
<p><%= @feedback.desc %></p>
<p><%= @feedback.data %></p>
<p><%= @feedback.resolvido %></p>
<p><%= @feedback.usuario %></p>
<%= link_to "voltar", feedbacks_path%>

app/views/feedbacks/update.html.erb
<h1>Feedbacks#update</h1>
<p>Find me in app/views/feedbacks/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar-geral navbar navbar-expand-lg ">
  <div class="container-fluid">
    <%= link_to "Home",root_path,class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Feedbacks",feedbacks_path,class: "nav-link active"%> 
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotrailsTer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "navbar", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
 
  </head>

  <body class="bg-dark text-light">
    <%= render "layouts/navbar" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
 
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bem vindo aos chamados</h1>
<p>Crie seu primeiro chamado</p>
<% if current_user %>
  <p> Bem vindo <%= current_user.email %>!</p>
  <p> você é um <%= current_user.role %></p>
  <p> texto grande </p>
  <%= link_to "Sair",destroy_user_session_path,'data-turbo-method': :delete ,class: "btn btn-danger"%>
<% else %>
  <p> você não está logado, por favor logar</p>
  <%= link_to "Logar", new_user_session_path,class: "btn btn-primary"%>
  <%= link_to "Crie sua conta", new_user_registration_path,class: "btn btn-success"%>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Editando o post</h1>

<%= form_with model: @post, data: { type: :hotwire } do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div class="">
        <%= form.submit 'Edit o post', class: 'btn btn-warning' %> 

  </div>
<%end%>

app/views/posts/index.html.erb
<h1>POSTS</h1>

<%= link_to  "crie seu post",new_post_path,class: "btn btn-info"%>
<table class="table text-light">
  <thead>
    <tr>
      <th> Title</th>
      <th> Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody data-target="post.row" data-action="click->post#show">
    <% @posts.each do |post|%>
      <tr>
        <td> <%= post.title %></td>
        <td> <%= post.body %></td>
        <td> <%= link_to "Show",post ,class: "btn btn-primary"%></td>
        <td> <%= link_to "Edit",edit_post_path(post),class: "btn btn-warning" %></td>
        <td> <%= button_to "Delete",post,method: :delete,data: {confirm: "está certo disso?"} ,class: "btn btn-danger"%></td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Crie o post</h1>

<%= form_with model: @post, data: { type: :hotwire } do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<%end%>

app/views/posts/show.html.erb
<h1><%= @post.title  %></h1>
<p> <%= @post.body %> </p>
<%= link_to "voltar aos posts",posts_path ,class: "btn btn-primary"%>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>